### PR TITLE
Docker contrib

### PR DESCRIPTION
**Pull request by robdyke**
- Docker container for ehrserver - #814 

Note that grails-app/conf/DataSource.groovy expects variables for development and test environments.

### CODE REVIEW

**Comment by robdyke** [comment]
Hummmmm

```
Configuring Spring Security Core ...
... finished configuring Spring Security Core
| Error 2018-12-05 18:11:47,728 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index arch_id_path_idx on data_value_index (archetype_id, archetype_path)
| Error 2018-12-05 18:11:47,734 [main] ERROR hbm2ddl.SchemaUpdate  - Specified key was too long; max key length is 767 bytes
| Error 2018-12-05 18:11:47,749 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index arch_path_idx on data_value_index (archetype_path)
| Error 2018-12-05 18:11:47,749 [main] ERROR hbm2ddl.SchemaUpdate  - Specified key was too long; max key length is 767 bytes
| Error Fatal error running tests: Spring security stateles secretKey not configured or empty. Please, set 'grails.plugin.security.stateless.secretKey' value in your Config.groovy (Use --stacktrace to see the full trace)
| Tests FAILED  - view reports in /home/travis/build/ppazos/cabolabs-ehrserver/target/test-reports
| Error Forked Grails VM exited with error
The command "./grailsw refresh-dependencies && ./grailsw "test-app -integration -echoOut" && ./grailsw "test-app -unit UserControllerSpec"" exited with 1.
```

**Comment by robdyke** [comment]
Hi @ppazos 

If this failure is because of `EHRSERVER_REST_SECRET`, then this needs to be added travis.yml for tests to run.

**Comment by ppazos** [comment]
@robdyke we do have it set but not on the travis config file, it is set on the travis site. The previous commits that passed the travis tests.

Also it depends on what is on the Config.groovy: | Error Fatal error running tests: Spring security stateles secretKey not configured or empty. Please, set 'grails.plugin.security.stateless.secretKey' value in your Config.groovy

REF: https://travis-ci.org/ppazos/cabolabs-ehrserver/jobs/463989206#L882

But your PR doesn't have any changes to Config.groovy...

I will try to download your branch and test locally ASAP.

**Comment by kargakis** [comment]
@robdyke @ppazos any chance to get this merged?

**Comment by ppazos** [comment]
@kargakis last time I checked the PR didn't pass the CI and had some files in the commit that shouldn't be changed if adding only the docker updates.

Also there are a couple of branches of the project that have more updated docker files. We need to ask them to merge those into the main repo.

**Comment by kargakis** [comment]
> Also there are a couple of branches of the project that have more updated docker files. We need to ask them to merge those into the main repo.

@ppazos that would be great, please do! Thanks

**Comment by robdyke** [comment]
Which is the most up-to-date Dockerfile @ppazos and I'll take a look.

/rob

**Comment by ppazos** [comment]
@robdyke detected 3 forks with modifications to the docker file, not sure which is the latest one, or which one is more complete or works, didn't tested them

https://github.com/popaaaandrei/cabolabs-ehrserver/commit/cfa306648b94ae2b0dede4cf063e9a47d943e942

https://github.com/ValleSaude/cabolabs-ehrserver/commit/874c6a4ba062750638aff0683e50cba5a45bd12b

https://github.com/romulobusatto/cabolabs-ehrserver/commit/aac7b2fa62a1b19f86a4b6f271177ff4e1d53bbc

**Pull request closed without merging**
